### ISSUE TITLE
carpet bomber gives +4 area damage, not +6

### ISSUE THREAD

**Issue by converal** [surmiran/karl#24]

**Comment by surmiran** [comment]
hey, thank you so much for continually pointing these things out. i've not been playing much drg lately and didn't pay much attention to the hotfixes.. so your feedback is really valuable!

**Comment by converal** [comment]
Thanks man. Actually other people notice stuff too, but it seems like it's only me who knows how to inform you about that :D When someone finds stat that doesn't match in game - he says smth like KARL is buggy in terms of OCs, I ensure to provide these finds directly to you there instead of just talking shit about great tool.

**Comment by surmiran** [comment]
Very much appreciated, i just don't have the time to check the discord or reddit these days. And cross checking every mod and OC would just be crazy 🤷‍♂ especially as the wiki is probably not always up to date either.. so thanks again :D
