### ISSUE TITLE
Flare Gun: Add Total Lighting Time

### ISSUE THREAD

**Issue by GoldMath** [surmiran/karl#3]
Hello,

It would be nice if the Scout **Flare Gun** could display a **Total Lighting Time** when tweaking mods.

Example: (4+18)*75=1650/60 
(MagazineSize+MaxAmmo)*Duration

**Total Lighting Time**: 27.5 minutes

Regards,

**Comment by surmiran** [comment]
Implemented, thanks very much for the idea :)
